version: "3.9"
services:

  api:
    container_name: csv_api
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0 --port=8000"
    volumes: 
      - app_data:/app
    env_file: ./.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: csv_db
    image: postgres:14.3-alpine
    restart: always
    environment:
           - POSTGRES_DB=${POSTGRES_DB}
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
    db_data:
    app_data:
    